### ISSUE TITLE
有一个报错想咨询一下作者，感谢

### ISSUE THREAD

**Issue by zhangzitenga** [yongzhuo/gemma-sft#2]
我在运行predict.py进行推理时，给了报错如下
Error while deserializing header: HeaderTooLarge
Traceback (most recent call last):
  File "/root/gemma-sft/gemma_sft/ft_gemma/predict.py", line 125, in load_model_state
    with safe_open(path_model, framework="pt", device=device) as f:
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/gemma-sft/gemma_sft/ft_gemma/predict.py", line 295, in <module>
    model = load_model_state(model=model, model_save_dir=MODEL_SAVE_DIR)
  File "/root/gemma-sft/gemma_sft/ft_gemma/predict.py", line 149, in load_model_state
    raise Exception("******load model error******")
Exception: ******load model error******
不清楚是什么原因，搜索这个报错都是与模型下载错误有关，这是否是因为没有在训练时调整权重精度，我训练部分信息如下
('base_model.model.model.embed_tokens.weight', torch.float32, False)
('base_model.model.model.layers.0.self_attn.q_proj.weight', torch.float32, False)
('base_model.model.model.layers.0.self_attn.q_proj.lora_A.weight', torch.float32, True)
('base_model.model.model.layers.0.self_attn.q_proj.lora_B.weight', torch.float32, True)
('base_model.model.model.layers.0.self_attn.k_proj.weight', torch.float32, False)
('base_model.model.model.layers.0.self_attn.k_proj.lora_A.weight', torch.float32, True)
('base_model.model.model.layers.0.self_attn.k_proj.lora_B.weight', torch.float32, True)
('base_model.model.model.layers.0.self_attn.v_proj.weight', torch.float32, False)
('base_model.model.model.layers.0.self_attn.v_proj.lora_A.weight', torch.float32, True)
('base_model.model.model.layers.0.self_attn.v_proj.lora_B.weight', torch.float32, True)
('base_model.model.model.layers.0.self_attn.o_proj.weight', torch.float32, False)

**Comment by zhangzitenga** [comment]
要修改权重精度的话，具体又要怎么修改

**Comment by yongzhuo** [comment]
看报错应该是safetensors的加载问题
1.transformers, safetensors版本是一样的？
2.你有训练[train.py](https://github.com/yongzhuo/gemma-sft/blob/master/gemma_sft/ft_gemma/train.py)，是ok的吗？
3.看这报错同bug [https://github.com/huggingface/safetensors/issues/414#issue-2060747836](https://github.com/huggingface/safetensors/issues/414#issue-2060747836)，你加载的是pytorch .bin文件，不是.safetensors，试试注释掉load_model_state中的
```python
if path_model.endswith(".safetensors"):
          from safetensors.torch import load_file, save_file
          from safetensors import safe_open
          state_dict = {}
          with safe_open(path_model, framework="pt", device="cpu") as f:
              for k in f.keys():
                  state_dict[k] = f.get_tensor(k)
### if path_model.endswith(".bin") or path_model.endswith(".pt"):
else:
    state_dict = torch.load(path_model, map_location=torch.device(device))
```
换成
```
state_dict = torch.load(path_model, map_location=torch.device(device))
```
试试
